/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import type {JSX} from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Cube006: THREE.Mesh
        Cube006_1: THREE.Mesh
    }
    materials: {
        ['Material.001']: THREE.MeshStandardMaterial
        ['Material.002']: THREE.MeshStandardMaterial
    }
}

export function Box(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/box.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <group scale={[1, 0.108, 1]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube006.geometry}
                    material={materials['Material.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube006_1.geometry}
                    material={materials['Material.002']}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/box.glb')