/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useMemo, createContext } from 'react'
import type { ReactNode } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type {ThreeElements} from "@react-three/fiber";

type GroupProps = ThreeElements['group']

type GLTFResult = GLTF & {
    nodes: {
        Rotator: THREE.Mesh
        Turbine: THREE.Mesh
        Mesh: THREE.Mesh
        Mesh_1: THREE.Mesh
        Circle002: THREE.Mesh
        Circle002_1: THREE.Mesh
    }
    materials: {
        BaseColor: THREE.MeshPhysicalMaterial
        Base: THREE.MeshStandardMaterial
        BlueStripe: THREE.MeshStandardMaterial
    }
}

export const context = createContext<any>(null!)

export function ModelInstances({ children, ...props }: Omit<GroupProps, 'ref'> & { children: ReactNode }) {
    const { nodes } = useGLTF('/windTurbine.glb') as unknown as GLTFResult
    const instances = useMemo(
        () => ({
            Rotator: nodes.Rotator,
            Turbine: nodes.Turbine,
            Mesh: nodes.Mesh,
            Mesh1: nodes.Mesh_1,
            Circle: nodes.Circle002,
            Circle1: nodes.Circle002_1,
        }),
        [nodes]
    )
    return (
        <Merged meshes={instances} {...props}>
            {(instances) => <context.Provider value={instances} children={children} />}
        </Merged>
    )
}

useGLTF.preload('/windTurbine.glb')