/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useContext } from 'react'
import type { JSX } from 'react'
import { context } from './ModelInstances'

export function WindTurbineModel(props: JSX.IntrinsicElements['group']) {
    const instances = useContext(context)

    return (
        <group {...props} dispose={null}>
            <instances.Rotator position={[0, 3.278, 0.011]}>
                <instances.Turbine position={[0, 0, -0.804]}>
                    <group position={[0, 0, 0.314]}>
                        <instances.Mesh />
                        <instances.Mesh1 />
                    </group>
                </instances.Turbine>
            </instances.Rotator>
            <group scale={[0.809, 1, 0.809]}>
                <instances.Circle />
                <instances.Circle1 />
            </group>
        </group>
    )
}
