/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
// import { useControls } from 'leva'
import * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
    nodes: {
        Rotator: THREE.Mesh
        Turbine: THREE.Mesh
        Mesh: THREE.Mesh
        Mesh_1: THREE.Mesh
        Circle002: THREE.Mesh
        Circle002_1: THREE.Mesh
    }
    materials: {
        Base: THREE.MeshStandardMaterial
        BaseColor: THREE.MeshStandardMaterial
        BlueStripe: THREE.MeshStandardMaterial
    }
}

export function WindTurbine(props: ThreeElements['group']) {
    // eslint-disable-next-line
    const offsetRef = useRef(Math.random());

    // const controls = useControls({
    //     speed: {
    //         value: 2,
    //         min: 0,
    //         max: 10,
    //         step: 0.01
    //     }
    // })

    const controls = {
        speed: 2,
    }

    const { nodes, materials } = useGLTF('./windTurbine.glb') as unknown as GLTFResult

    const propellerRef = useRef<THREE.Mesh>(null!)
    const rotatorRef = useRef<THREE.Mesh>(null!)

    useFrame((state) => {
        const elapsedTime = state.clock.elapsedTime

        if (propellerRef.current) {
            propellerRef.current.rotation.z = offsetRef.current + elapsedTime * controls.speed
        }

        if (rotatorRef.current) {
            rotatorRef.current.rotation.y = offsetRef.current + Math.sin(elapsedTime) * controls.speed * 0.2
        }
    })

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                ref={rotatorRef}
                geometry={nodes.Rotator.geometry}
                material={materials.BaseColor}
                position={[0, 3.278, 0.011]}>
                <mesh
                    castShadow
                    receiveShadow
                    ref={propellerRef}
                    geometry={nodes.Turbine.geometry}
                    material={materials.Base}
                    position={[0, 0, -0.804]}>
                    <group position={[0, 0, 0.314]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh.geometry}
                            material={materials.BaseColor}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh_1.geometry}
                            material={materials.BlueStripe}
                        />
                    </group>
                </mesh>
            </mesh>
            <group scale={[0.809, 1, 0.809]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle002.geometry}
                    material={materials.Base}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle002_1.geometry}
                    material={materials.BaseColor}
                />
            </group>
        </group>
    )
}

useGLTF.preload('./windTurbine.glb')
