/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { type GLTF } from 'three-stdlib';

import {
    CHUNK_SIZE,
    GRID_SIZE_Z,
    uRoadWidth,
    uSideRoadX,
} from '../../utils/constants';
import { getSurfaceY } from '../../utils/elevation';
import useGame from '../../store/useGame';

type GLTFResult = GLTF & {
    nodes: { roadSign: THREE.Mesh };
    materials: { 'plain wood': THREE.Material };
};

export function RoadSignModel() {
    const { nodes, materials } = useGLTF(
        './models/roadSign/roadSign.glb',
    ) as unknown as GLTFResult;
    const playerPosition = useGame((state) => state.playerPosition);

    const groupRef = useRef<THREE.Group>(null);

    useFrame(() => {
        if (!groupRef.current) return;

        // Place on terrain surface
        groupRef.current.position.y = getSurfaceY(
            groupRef.current.position,
            playerPosition,
        );
    });

    return (
        <group
            ref={groupRef}
            scale={0.6}
            position={[
                uSideRoadX + uRoadWidth,
                0,
                ((GRID_SIZE_Z - 1) * CHUNK_SIZE) / 2 + 5,
            ]}
            rotation-y={3.7}
            dispose={null}
        >
            <mesh
                castShadow
                geometry={nodes.roadSign.geometry}
                material={materials['plain wood']}
            />
        </group>
    );
}

useGLTF.preload('/roadSign.glb');
