/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { type JSX } from 'react';
import { useGLTF } from '@react-three/drei';
import { type GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Tree: THREE.Mesh;
    };
};

export function TreeModel(props: JSX.IntrinsicElements['group']) {
    const { nodes } = useGLTF(
        './models/tree/tree.glb',
    ) as unknown as GLTFResult;

    return (
        <group {...props} scale={3} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Tree.geometry}>
                <meshStandardMaterial color="#936d2f" />
            </mesh>
        </group>
    );
}

useGLTF.preload('./models/tree/tree.glb');
