/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function ConstructionSignModel(props: any) {
    const { nodes, materials } = useGLTF(
        './models/constructionSign/Construction_sign.glb',
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ) as unknown as any;
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.group1176710984.geometry}
                material={materials.mat21}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.group790830455.geometry}
                material={materials.mat21}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.group56958267.geometry}
                material={materials.mat21}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.group2019904400.geometry}
                material={materials.mat21}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1969675137.geometry}
                material={materials.mat21}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1969675137_1.geometry}
                material={materials.mat23}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1969675137_2.geometry}
                material={materials.mat12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1899794681.geometry}
                material={materials.mat21}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1899794681_1.geometry}
                material={materials.mat23}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1899794681_2.geometry}
                material={materials.mat12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1273453722.geometry}
                material={materials.mat21}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1273453722_1.geometry}
                material={materials.mat23}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1273453722_2.geometry}
                material={materials.mat12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1038710627.geometry}
                material={materials.mat12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1038710627_1.geometry}
                material={materials.mat21}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh1038710627_2.geometry}
                material={materials.mat23}
            />
        </group>
    );
}

useGLTF.preload('./models/constructionSign/Construction_sign.glb');
