/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useMemo, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { FARM_BOUNDS, FARM_WIDTH } from '../../utils/constants';
import {
    farmDepthMaterialMaterial,
    farmUniforms,
} from '../../materials/farmMaterial';
import CustomShaderMaterial from 'three-custom-shader-material/vanilla';
import { farmVertexShader } from '../../shaders';

export function FarmModel() {
    const { nodes, materials } = useGLTF('./models/farm/farm.glb');

    const farmMaterial = useMemo(
        () =>
            new CustomShaderMaterial({
                // MeshStandardMaterial props
                metalness: 0,
                roughness: 0.8,
                frustumCalled: false,

                // Shader (CSM props)
                vertexShader: farmVertexShader,
                uniforms: farmUniforms,
                baseMaterial: materials.baked,
            }),
        [materials],
    );

    return (
        <group
            position={[
                FARM_BOUNDS[0][0],
                0,
                FARM_BOUNDS[0][1] + FARM_WIDTH / 2,
            ]}
            dispose={null}
        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.farm.geometry}
                material={farmMaterial}
                customDepthMaterial={farmDepthMaterialMaterial}
            />
        </group>
    );
}
