/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useMemo } from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { type GLTF } from 'three-stdlib';
import CustomShaderMaterial from 'three-custom-shader-material/vanilla';

import { FARM_BOUNDS, FARM_WIDTH } from '../../utils/constants';
import {
    farmDepthMaterialMaterial,
    farmUniforms,
} from '../../materials/farmMaterial';
import { farmVertexShader } from '../../shaders';

type GLTFResult = GLTF & {
    nodes: { farm: THREE.Mesh };
    materials: { baked: THREE.Material };
};

export function FarmModel() {
    const { nodes, materials } = useGLTF(
        './models/farm/farm.glb',
    ) as unknown as GLTFResult;

    const farmMaterial = useMemo(
        () =>
            new CustomShaderMaterial({
                // MeshStandardMaterial props
                metalness: 0,
                roughness: 0.8,

                // Shader (CSM props)
                vertexShader: farmVertexShader,
                uniforms: farmUniforms,
                baseMaterial: materials.baked.clone(),
            }),
        [materials],
    );

    useEffect(() => {
        return () => farmMaterial.dispose();
    }, [farmMaterial]);

    return (
        <group
            position={[
                FARM_BOUNDS[0][0],
                0,
                FARM_BOUNDS[0][1] + FARM_WIDTH / 2,
            ]}
            dispose={null}
        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.farm.geometry}
                material={farmMaterial}
                customDepthMaterial={farmDepthMaterialMaterial}
                frustumCulled={false}
            />
        </group>
    );
}
