/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {FARM_BOUNDS, FARM_WIDTH} from "../../utils/constants";

export function FarmModel() {
    const { nodes, materials } = useGLTF('./models/farm/farm.glb')
    return (
        <group position={[FARM_BOUNDS[0][0], 0, FARM_BOUNDS[0][1] + FARM_WIDTH / 2]} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.farm.geometry}
                material={materials.baked}
            />
        </group>
    )
}
