/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react';
import { useFrame, type ThreeElements } from '@react-three/fiber';
import * as THREE from 'three';
import { useGLTF, useAnimations } from '@react-three/drei';

import useGame from '../../store/useGame';
import { getWindTurbinePosition } from '../../utils/decorations';

export function CowModel(props: ThreeElements['group']) {
    const cowRef = useRef<THREE.Group>(null);

    const { nodes, materials, animations } = useGLTF(
        './models/cow/Cow.glb',
    ) as unknown as {
        nodes: Record<string, THREE.SkinnedMesh>;
        materials: Record<string, THREE.Material>;
        animations: THREE.AnimationClip[];
    };
    const { actions, mixer } = useAnimations(animations, cowRef);

    const playerWasInRange = useRef(false);

    const playerPosition = useGame((state) => state.playerPosition);

    useEffect(() => {
        const attackAction = actions['AnimalArmature|Attack_Headbutt'];
        const idleAction = actions['Idle'];
        if (!attackAction || !idleAction) return;

        attackAction.setLoop(THREE.LoopOnce, 1);
        // eslint-disable-next-line react-hooks/immutability
        attackAction.clampWhenFinished = true;

        idleAction.play();

        const onFinished = () => {
            attackAction.stop();
            idleAction.reset().fadeIn(0.2).play();
        };

        mixer.addEventListener('finished', onFinished);

        return () => mixer.removeEventListener('finished', onFinished);
    }, [actions, mixer]);

    useFrame(() => {
        if (!cowRef.current) return;

        // Place on terrain surface
        cowRef.current.position.y = getWindTurbinePosition(
            cowRef.current.position,
            playerPosition,
        );

        const distanceToPlayer =
            cowRef.current.position.distanceToSquared(playerPosition);

        const attackAction = actions['AnimalArmature|Attack_Headbutt'];
        const idleAction = actions['Idle'];
        if (!attackAction || !idleAction) return;

        // Animate if the player is close
        if (distanceToPlayer < 70 && !playerWasInRange.current) {
            playerWasInRange.current = true;

            attackAction.reset().play();
            idleAction.crossFadeTo(attackAction, 0.2);
        }

        if (distanceToPlayer > 71 && playerWasInRange.current) {
            playerWasInRange.current = false;
        }
    });

    return (
        <group ref={cowRef} {...props} dispose={null}>
            <group name="Root_Scene">
                <group name="RootNode">
                    <group
                        name="AnimalArmature"
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <primitive object={nodes.Body} />
                        <primitive object={nodes.IKBackLegL} />
                        <primitive object={nodes.IKFrontLegL} />
                        <primitive object={nodes.IKBackLegR} />
                        <primitive object={nodes.IKFrontLegR} />
                    </group>
                    <group
                        name="Cow"
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    >
                        <skinnedMesh
                            name="Cow_1"
                            geometry={nodes.Cow_1.geometry}
                            material={materials.Main}
                            skeleton={nodes.Cow_1.skeleton}
                        />
                        <skinnedMesh
                            name="Cow_2"
                            geometry={nodes.Cow_2.geometry}
                            material={materials.Main_Light}
                            skeleton={nodes.Cow_2.skeleton}
                        />
                        <skinnedMesh
                            name="Cow_3"
                            geometry={nodes.Cow_3.geometry}
                            material={materials.Muzzle}
                            skeleton={nodes.Cow_3.skeleton}
                        />
                        <skinnedMesh
                            name="Cow_4"
                            geometry={nodes.Cow_4.geometry}
                            material={materials.Hooves}
                            skeleton={nodes.Cow_4.skeleton}
                        />
                        <skinnedMesh
                            name="Cow_5"
                            geometry={nodes.Cow_5.geometry}
                            material={materials.Eye_Black}
                            skeleton={nodes.Cow_5.skeleton}
                        />
                        <skinnedMesh
                            name="Cow_6"
                            geometry={nodes.Cow_6.geometry}
                            material={materials.Eye_White}
                            skeleton={nodes.Cow_6.skeleton}
                        />
                        <skinnedMesh
                            name="Cow_7"
                            geometry={nodes.Cow_7.geometry}
                            material={materials.Horns}
                            skeleton={nodes.Cow_7.skeleton}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('./models/cow/Cow.glb');
