/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { type ThreeElements } from '@react-three/fiber';
import * as THREE from 'three';

type GLTFResult = {
    nodes: {
        [key: string]: THREE.Mesh;
    };
    materials: {
        [key: string]: THREE.Material;
    };
};

export function Bicycle(props: ThreeElements['group']) {
    const { nodes, materials } = useGLTF(
        './models/bicycle/BicycleDecimated.glb',
    ) as unknown as GLTFResult;

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.BackWheel.geometry}
                material={materials.BicyclePalette}
                position={[-2.086, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Frame.geometry}
                material={materials.BicyclePalette}
                position={[-0.279, -0.109, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.FrontWheel.geometry}
                material={materials.BicyclePalette}
                position={[2.105, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.HandleBar.geometry}
                material={materials.BicyclePalette}
                position={[2.105, 0, 0.338]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.LeftPedal.geometry}
                material={materials.BicyclePalette}
                position={[-0.279, -0.513, -0.778]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.PedalRotor.geometry}
                material={materials.BicyclePalette}
                position={[-0.279, -0.109, -0.002]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.RightPedal.geometry}
                material={materials.BicyclePalette}
                position={[-0.279, 0.292, 0.775]}
            />
        </group>
    );
}

useGLTF.preload('./models/bicycle/BicycleDecimated.glb');
