/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { type ThreeElements } from '@react-three/fiber';
import * as THREE from 'three';

type GLTFResult = {
    nodes: {
        [key: string]: THREE.Mesh;
    };
    materials: {
        [key: string]: THREE.Material;
    };
};

export function Bicycle(props: ThreeElements['group']) {
    const { nodes, materials } = useGLTF(
        './models/bicycle/MyVeryOwnBicycle.glb',
    ) as unknown as GLTFResult;

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Crank.geometry}
                material={materials.Metal}
                position={[-0.28, -0.109, -0.002]}
            />
            <group position={[-0.738, 1.925, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Frame_1.geometry}
                    material={materials.Handle}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Frame_2.geometry}
                    material={materials.Rim}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Frame_3.geometry}
                    material={materials.Metal}
                />
            </group>
            <group position={[1.644, 2.429, 0.001]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.HandleBar_1.geometry}
                    material={materials.Handle}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.HandleBar_2.geometry}
                    material={materials.Rim}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.PedalLeft.geometry}
                material={materials.Pedal}
                position={[-0.28, -0.513, -0.778]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.PedalRight.geometry}
                material={materials.Pedal}
                position={[-0.28, 0.292, 0.775]}
            />
            <group position={[2.105, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WheelFront_1.geometry}
                    material={materials.TireInner}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WheelFront_2.geometry}
                    material={materials.Tire}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WheelFront_3.geometry}
                    material={materials.Metal}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WheelFront_4.geometry}
                    material={nodes.WheelFront_4.material}
                />
            </group>
            <group position={[-2.087, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WheelRear_1.geometry}
                    material={materials.TireInner}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WheelRear_2.geometry}
                    material={materials.Tire}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WheelRear_3.geometry}
                    material={materials.Metal}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.WheelRear_4.geometry}
                    material={nodes.WheelRear_4.material}
                />
            </group>
        </group>
    );
}

useGLTF.preload('./models/bicycle/MyVeryOwnBicycle.glb');
