/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { type ThreeElements } from '@react-three/fiber';
import * as THREE from 'three';
import { type RefObject } from 'react';

type GLTFResult = {
    nodes: {
        [key: string]: THREE.Mesh;
    };
    materials: {
        [key: string]: THREE.Material;
    };
};

type Props = {
    steeringRef: RefObject<THREE.Mesh | null>;
    frontWheelRef: RefObject<THREE.Mesh | null>;
    rearWheelRef: RefObject<THREE.Mesh | null>;
    crankRef: RefObject<THREE.Mesh | null>;
    leftPedalRef: RefObject<THREE.Mesh | null>;
    rightPedalRef: RefObject<THREE.Mesh | null>;
} & ThreeElements['group'];

export function Bicycle({
    steeringRef,
    frontWheelRef,
    rearWheelRef,
    crankRef,
    leftPedalRef,
    rightPedalRef,
    ...props
}: Props) {
    const { nodes, materials } = useGLTF(
        './models/bicycle/BicycleDecimated.glb',
    ) as unknown as GLTFResult;

    return (
        <group {...props} dispose={null}>
            <mesh
                ref={steeringRef}
                castShadow
                receiveShadow
                geometry={nodes.HandleBar.geometry}
                material={materials.BicyclePalette}
                position={[1.546, 1.822, -0.001]}
            >
                <mesh
                    ref={frontWheelRef}
                    castShadow
                    receiveShadow
                    geometry={nodes.FrontWheel.geometry}
                    material={materials.BicyclePalette}
                    position={[0.559, -1.822, 0]}
                />
            </mesh>

            <mesh
                ref={rearWheelRef}
                castShadow
                receiveShadow
                geometry={nodes.BackWheel.geometry}
                material={materials.BicyclePalette}
                position={[-2.086, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Frame.geometry}
                material={materials.BicyclePalette}
                position={[-0.279, -0.109, 0]}
            />

            <mesh
                ref={crankRef}
                castShadow
                receiveShadow
                geometry={nodes.PedalRotor.geometry}
                material={materials.BicyclePalette}
                position={[-0.279, -0.109, -0.002]}
            >
                <mesh
                    ref={leftPedalRef}
                    castShadow
                    receiveShadow
                    geometry={nodes.LeftPedal.geometry}
                    material={materials.BicyclePalette}
                    position={[0, -0.404, -0.777]}
                />
                <mesh
                    ref={rightPedalRef}
                    castShadow
                    receiveShadow
                    geometry={nodes.RightPedal.geometry}
                    material={materials.BicyclePalette}
                    position={[0, 0.402, 0.776]}
                />
            </mesh>
        </group>
    );
}

useGLTF.preload('./models/bicycle/BicycleDecimated.glb');
